#!/usr/bin/env python3
"""Vendor the stack-neutral harness layer into a consuming repository.

Layer A reaches Claude Code as a plugin, resolved outside the working tree. Every other
harness reads repo-relative paths only, so it gets the same content as ordinary committed
files under `.agents/vendor/harness/`, pinned to a `harness` commit.

Vendored files are generated. Editing one in the consuming repo is the drift this whole
arrangement exists to prevent, so `check` fails on a hand edit as loudly as it fails on a
stale pin.

Stdlib only, deliberately: this runs in the Node repo with the runner's preinstalled
python3 and no setup step -- the same constraint the main generator is written under.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

# What layer A actually ships. Paths are relative to the plugin root.
VENDORED = ("docs/agents",)

PLUGIN_ROOT = "plugins/harness"
VENDOR_DIR = Path(".agents/vendor/harness")
MANIFEST_NAME = "MANIFEST.json"

# The branch a consuming repo's own v2 vendors from. Its main uses the plugin instead.
SOURCE_BRANCH = "v2"


def run(args: list[str], cwd: Path) -> str:
    proc = subprocess.run(  # noqa: S603
        args, cwd=cwd, capture_output=True, text=True, check=False
    )
    if proc.returncode != 0:
        raise SystemExit(f"{' '.join(args)} failed in {cwd}:\n{proc.stderr.strip()}")
    return proc.stdout.strip()


def run_optional(args: list[str], cwd: Path, fallback: str) -> str:
    """For facts that are nice to record but must not stop a sync.

    A harness checkout with no `origin` is a normal state -- a fresh clone before the
    remote is added, or a CI checkout that fetched by URL. The pin in `sha` is what the
    freshness check actually reads; `source` is there for a human reading the manifest.
    """
    proc = subprocess.run(  # noqa: S603
        args, cwd=cwd, capture_output=True, text=True, check=False
    )
    return proc.stdout.strip() if proc.returncode == 0 else fallback


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_files(harness: Path) -> list[Path]:
    """Every tracked file layer A ships, relative to the plugin root.

    Tracked, not walked -- an untracked file in a local harness checkout must never
    reach a consuming repo. That defect already shipped once through the main generator.
    """
    out: list[Path] = []
    for entry in VENDORED:
        listing = run(["git", "ls-files", "-z", f"{PLUGIN_ROOT}/{entry}"], cwd=harness)
        for name in filter(None, listing.split("\0")):
            out.append(Path(name).relative_to(PLUGIN_ROOT))
    return sorted(out)


def build_manifest(harness: Path, files: list[Path]) -> dict:
    return {
        "$comment": "Generated by harness scripts/vendor_sync.py. Do not edit by hand.",
        "source": run_optional(
            ["git", "remote", "get-url", "origin"], cwd=harness, fallback="(no origin remote)"
        ),
        "branch": SOURCE_BRANCH,
        "sha": run(["git", "rev-parse", "HEAD"], cwd=harness),
        "files": {
            str(f): sha256(harness / PLUGIN_ROOT / f) for f in files
        },
    }


def cmd_sync(harness: Path, target: Path) -> int:
    files = source_files(harness)
    if not files:
        raise SystemExit(f"no layer A files found under {harness / PLUGIN_ROOT}")

    dest = target / VENDOR_DIR
    if dest.exists():
        shutil.rmtree(dest)

    for f in files:
        out = dest / f
        out.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(harness / PLUGIN_ROOT / f, out)

    manifest = build_manifest(harness, files)
    (dest / MANIFEST_NAME).write_text(json.dumps(manifest, indent=2) + "\n")

    print(f"vendored {len(files)} file(s) into {VENDOR_DIR} at {manifest['sha'][:9]}")
    for f in files:
        print(f"  {f}")
    return 0


def cmd_check(target: Path, harness: Path | None) -> int:
    dest = target / VENDOR_DIR
    manifest_path = dest / MANIFEST_NAME
    if not manifest_path.exists():
        print(f"FAIL: no vendored layer A at {VENDOR_DIR}. Run `vendor_sync.py sync`.")
        return 1

    manifest = json.loads(manifest_path.read_text())
    problems: list[str] = []

    # Integrity -- offline. Catches a hand edit to a generated file.
    recorded = manifest["files"]
    present = {
        str(p.relative_to(dest))
        for p in dest.rglob("*")
        if p.is_file() and p.name != MANIFEST_NAME
    }
    for name, digest in recorded.items():
        path = dest / name
        if not path.exists():
            problems.append(f"missing: {name}")
        elif sha256(path) != digest:
            problems.append(f"edited by hand: {name} -- layer A is generated, edit it in harness")
    for extra in sorted(present - set(recorded)):
        problems.append(f"not part of layer A: {extra}")

    # Freshness -- needs the harness repo. Skipped when it was not supplied.
    if harness is not None:
        pinned = manifest["sha"]
        head = run(["git", "rev-parse", f"origin/{SOURCE_BRANCH}"], cwd=harness)
        if pinned != head:
            behind = run(
                ["git", "rev-list", "--count", f"{pinned}..{head}"], cwd=harness
            )
            problems.append(
                f"stale pin: vendored layer A is {behind} commit(s) behind "
                f"harness@{SOURCE_BRANCH} ({pinned[:9]} -> {head[:9]}). "
                f"Run `vendor_sync.py sync`."
            )
    else:
        print("note: harness checkout not supplied -- integrity checked, freshness not")

    if problems:
        print("FAIL: vendored layer A is out of date with harness")
        for p in problems:
            print(f"  - {p}")
        return 1

    print(f"OK: vendored layer A matches harness@{manifest['sha'][:9]}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_sync = sub.add_parser("sync", help="copy layer A into the target repo and pin it")
    p_sync.add_argument("--harness", type=Path, required=True)
    p_sync.add_argument("--target", type=Path, default=Path("."))

    p_check = sub.add_parser("check", help="verify the vendored copy is intact and current")
    p_check.add_argument("--target", type=Path, default=Path("."))
    p_check.add_argument(
        "--harness", type=Path, default=None, help="omit to check integrity only"
    )

    args = parser.parse_args()
    if args.cmd == "sync":
        return cmd_sync(args.harness.resolve(), args.target.resolve())
    return cmd_check(
        args.target.resolve(), args.harness.resolve() if args.harness else None
    )


if __name__ == "__main__":
    sys.exit(main())
